Global DPK Recon/GIC.MVCWeb/Controllers/TransactionHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GIC.MVCWeb.Controllers
{
    public class TransactionHistoryController : Controller
    {
        //
        // GET: /DataQuery/

        public ActionResult Index()
        {
            ViewBag.Message = "This is Data Query web page!";

            List<SelectListItem> list = new List<SelectListItem>
            {
                new SelectListItem { Text = "C10000", Value = "1"},
                new SelectListItem { Text = "C40000", Value = "2"},
                new SelectListItem { Text = "C60000", Value = "3"},
                new SelectListItem { Text = "BRH", Value = "4"},
                new SelectListItem { Text = "DAO", Value = "5"},
                new SelectListItem { Text = "E10000", Value = "6"},
                new SelectListItem { Text = "I10000", Value = "7"},
                new SelectListItem { Text = "M10000", Value = "8"}
            };

            ViewData["ccnlist"] = new SelectList(list);

            return View();
        }

        //
        // GET: /DataQuery/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }        
    }
}

Global DPK Recon/GIC.MVCWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>         
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/My97DatePicker/WdatePicker.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>DPK Traceability Tool</h1>
            </div>
            <div id="logindisplay">
                Welcome <strong>@User.Identity.Name</strong>!
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>*@

                    <li>@Html.ActionLink("Transaction History", "Index", "TransactionHistory")</li>
                    <li>@Html.ActionLink("Discrepancy", "Index", "Discrepancy")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>